version: "3.3"

services:

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    networks:
      - gateway
    labels:
      - "traefik.enable=true"
      - "traefik.backend=whoami"
      - "traefik.docker.network=web"
      - "traefik.http.routers.whoami.rule=(Host(`debian`) && PathPrefix(`/whoami`))"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  gateway:
    external: true
